version: '3'

includes:
  default: https://raw.githubusercontent.com/vanyda-official/taskfile-default/main/tasks.yaml
  git: https://raw.githubusercontent.com/vanyda-official/taskfile-git/main/tasks.yaml
  markdownlint: ./tasks.yaml

dotenv:
  - .env
  - .env.default